---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: user-ns2
  annotations:
    application.thumbnail: "1"
spec:
  displayName: hello-world-app